# apps/overlays/dev/patches/backend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: backend
        image: httpd:2.4
        env:
        - name: NODE_ENV
          value: development
        - name: MONGODB_URI
          value: mongodb://mongodb:27017/dev
